### PR TITLE
Source side implementation

### PR DESCRIPTION
**Pull request by edurenye**
Rebased the pull #172 , just trying to speed up issue #4

### CODE REVIEW

**Comment by albfan** [comment]
Will review today, thanks for working on this.

Btw, there's an initiative under GNOME based on miracast.

https://github.com/benzea/gnome-screencast

Take a look and join us if you want to see this feature on your laptop

**Comment by Arzte** [comment]
@albfan Did you ever get a chance to review this PR?

(sorry if I'm being a bother here, just been a few days)

**Comment by albfan** [comment]
Sorry, didn't get to review it yet. Hope to do soon

**Comment by albfan** [comment]
btw: there's a https://github.com/albfan/miraclecast/tree/derekdai-master-squashed where I squashed all the back and forth in derekdai fork. Maybe rebase that branch would be a better option

**Comment by AtesComp** [comment]
The error is as listed:
```
/source/src/wifi/wifid-link.c: In function 'link_set_config_methods':
/source/src/wifi/wifid-link.c:393:1: error: expected declaration or statement at end of input
 }
 ^
```
In file "src/wifi/wifid-link.c" at line 173 there is no ending "}" for function "link_set_config_methods"
Adding fixes compile.

**Comment by AtesComp** [comment]
I compiled with autotools and seemed to finish ok, but it didn't compile the dispctl tool.

I then used cmake and the compile failed because the src/disp CMakeList.txt file needs directives for GLIB2 includes and libs.

**Comment by albfan** [comment]
@AtesComp that kind of fixes are on my squashed branch https://github.com/albfan/miraclecast/commit/56f9d44b19caa646c9d0981fc9fd503d90d9150e, that's why doesn't make much sense to me to keep this MR open. code do not even compile

**Comment by AtesComp** [comment]
Its hard to tell which particular branch you continue to reference as it doesn't show up in the branch listing since its not named.  It's also is difficult to tell which branch is the most up to date.  So please make this repository make sense.  Are you referring to the "docker" branch or "56f9d44b19"?

Please update the readme file for your prefered branch with updated instructions for the operational use of the software--the use of dispctl in the "documentation" section.

**Comment by AtesComp** [comment]
I suppose you mean the "derekdai-master-squashed" branch which shows up as "stale".  If this is the branch, please update the readme there.

**Comment by albfan** [comment]
Update README?

**Comment by AtesComp** [comment]
Yes, the README.md file.  In this or the derickdai-master-squashed branch (I've switched).  The "Documentation" section lists steps for sink and peer, but these branches used the miraclecast-dispd and miraclecast-wifid services to automate switching NetworkManager with dbus.  So, miracle-dispctl (and miracle-wifictl) need updated documentation there.

**Comment by albfan** [comment]
There're lot of noise in @derekdai PR. I just squashed to avoid rebase things like enable audio, disable audio which happens in that fork, but in the end I need to patch it, so I just want to notice that. It is supposed implementation should keep reviews and rework there in #172, but it stops to get progress so I guess we are not in a step where we can update docs about how it should work.

The whole idea is to enable Wifi Direct (through a dbus setting that could be trigger in gnome-control-center at some point) so you save battery when not using miracast, and then enable miracast where a service like miracle-dispd manages everything.

I'm collapsing this days comments with long output with `<details></details>` so one could follow comments on PR, where all the info about it should be avaliable.

@AtesComp you can always suggest a PR on top of `dereckdai-master-squashed` and I will be happy to merge your suggestions.

As said, I will close this PR, it doesn't even compile so just confuse people looking for source implementation

**Pull request closed without merging**
