### PR TITLE
Option to use elogind instead of systemd

### PR DESCRIPTION
**Pull request by Perlovka**
Hi, this patch is based on https://github.com/albfan/miraclecast/pull/317
* CMake option: -DUSE_SYSTEMD=OFF (ON is the default)
* Meson option: -Duse-systemd=false (true is the default)

Both CMake and Meson builds ran successful.
Binaries compiled with CMake has been tested successfully (screen cast from android to laptop)

### CODE REVIEW

**Comment by albfan** [comment]
Looks good, thanks. See there's an autotools buildsystem too. Can you tweak that too?

**Comment by Perlovka** [comment]
@albfan I've tried my best, not familiar with autotools ;)
Autotools patch has no options, it will detect which package is installed (systemd or elogind) and will build against it.
Build tested with elogind - works for me.

**Comment by albfan** [comment]
Thanks a lot, I postponed for some time to enable CI on PR, will setup this and if this just works will merge it.

Thanks a lot for this

**Comment by albfan** [comment]
Hmm, maybe you have elogind and systemd at same time installed?

I miss using HAVE_SYSTEMD to exclude some `#includes` like #441 

@Perlovka can you check it?

**Comment by albfan** [comment]
this is superseed by #441, autotools management is more explicit and dependencies are managed better with DEPS

**Pull request closed without merging**
