### PR TITLE
WIP: Miracast source side implementation

### PR DESCRIPTION
**Pull request by derekdai**
Hi albfan:

What's in this PR
- a unified interface to provide both source and sink functionality
- source side RTSP protocol (partial implemented)
- DBus control interface
- a shell script to demo how to use miracle-wfdctl

### CODE REVIEW

**Comment by albfan** [comment]
Awesome. I guess I will ha e no time this week for review it, but it's on my list for sure.

Talk soon

**Comment by derekdai** [comment]
Hi @albfan, the reason my code build failed is because it uses generic selection from c11, although I do have pass -std=c11 to gcc, but the feature is merged at gcc 4.9. Can you help to upgrade when available? Thanks.

**Comment by albfan** [comment]
Really want to dig into this, but seems a busy month, sorry.

**Comment by derekdai** [comment]
No problem ;)

**Comment by derekdai** [comment]
Hi @albfan, since there are too many (and keep coming) small commits, I will close this PR and create it when you are available in case I confusing people.

**Comment by albfan** [comment]
I see commits like disable audio, etc, that do not make much sense. I think is better for you to make a branch for PR (wip/source) and cherry-pick from your master when a change is ready and makes sense. As that branch is a wip you can squash and rebase on it and people will not get confused (that's expected on a wip).

Main idea is to keep as few commits that represent atomic changes to implement this feature.

**Comment by derekdai** [comment]
You are right. So I will close this PR first, and do what you suggests, then PR again once you are available.

**Comment by albfan** [comment]
Just finished some work to allow miraclecast to work on openembedded devices. 

I will cherry-pick/squash all those commits and show you an idea of how this PR can be shaped. I'm sure there's a lot of work we can pick directly to master right now.

I will rebase this on top of last commits to master

talk soon!

**Comment by derekdai** [comment]
Sounds cool! Or, you can give me some tips about how to do it, then I finish the rest.

**Comment by albfan** [comment]
I have done:

    $ git fetch origin pull/172/head:wip/source-impl
    $ git reset $(git merge-base master HEAD)

so here it is https://github.com/albfan/miraclecast/tree/wip/source-impl

I'm sure that's not enough to see all the work (as some commits will be hidden by others) but there's a lot of good stuff here.

Ideas to work on:

- demo should be on res directory (suggestion for dir structure are welcomed)
- there's no autotools stuff (no problem just mention for me) See meson build is also good to have #180 
- about debian files, I like the idea of vanilla upstream https://wiki.debian.org/PackagingWithGit#Upstream_import_methods
so this project keeps focused on build agnostic, same as arch linux is keeped on https://github.com/albfan/aur-miraclecast
- things like fullscreen can be added isolate as seems ready and useful without direct relation with this feature
- Seems like https://github.com/albfan/miraclecast/pull/135 was cherry-picked on this series of commits (avoid that)

I didn't test it at all, but after adding vala-dbus-binding-tool everything compiles correctly so seems is just a matter of remove unrelated things, move things to correct dir and split work in several understandable commits

**Comment by derekdai** [comment]
> so here it is https://github.com/albfan/miraclecast/tree/wip/source-impl
I see. In the near future, I can create a new branch, squeeze the commits int it, then create a PR against it, right?

> demo should be on res directory (suggestion for dir structure are welcomed)
No problem (I used to put it in res/, but after files keep adding, I feel maybe it's not so good to mix all these file in res/, so I move it to the demo/ as temp place).

> there's no autotools stuff (no problem just mention for me) See meson build is also good to have #180
Here is the branch I am working on, just try to replace cmake 1:1
https://github.com/derekdai/miraclecast/tree/build-with-meson

> about debian files, I like the idea of vanilla upstream
OK, I will study it

> things like fullscreen can be added isolate as seems ready and useful without direct relation with this feature
Not quite sure what this I understand correctly. Do you mean the gstreamer things can be extracted from the miracle-dispd into an isolated program?

> Seems like #135 was cherry-picked on this series of commits (avoid that)
Yes, currently I am using it as temp solution to co-exists with NetworkManager

**Comment by albfan** [comment]
Lot of things almost ready. Divide and conquer. I will do myself in some days. 

For example:

- Added resolutions seems to fix integration with lot of mobile devices.
- About fullscreen is just something that can be added to gstplayer directly
- Coexist with networkmanager is a feature long wanted, any progress on that would be appreciated (I will try to extract that) Join us on https://riot.im/app/#/room/#freenode_#nm:matrix.org to collaborate in https://wiki.gnome.org/NetworkManager/WifiDirect if you want

**Comment by derekdai** [comment]
> Added resolutions seems to fix integration with lot of mobile devices
This one, definitely will add. But I am fix the connectivity issue, handle it latter.

> About fullscreen is just something that can be added to gstplayer directly
I see.

> Coexist with networkmanager is a feature long wanted, any progress on that would be appreciated (I will try to extract that) Join us on https://riot.im/app/#/room/#freenode_#nm:matrix.org to collaborate in https://wiki.gnome.org/NetworkManager/WifiDirect if you want
No problem.

**Comment by albfan** [comment]
@derekdai tested your source branch.

1. meson build do not install service files, am I right? cmake does
2. I need to run with sudo
3. I use this app as sink https://play.google.com/store/apps/details?id=jp.ddo.pgnishikawa.wfdsinkemu&hl=es
4. Cannot pass from p2p group formation (mac anonymize to 00:00:00:00:00:00)
```
$ G_MESSAGES_DEBUG=all miracle-dispctl -p 00:00:00:00:00:00
miracle-dispctl: peer-mac=00:00:00:00:00:00
miracle-dispctl: display=:0
miracle-dispctl: authority=/home/alberto/.Xauthority
miracle-dispctl: interface=wlan0
miracle-dispctl: wfd_subelemens=000600001c4400c8
miracle-dispctl: monitor-num=0
** INFO: dispctl.vala:284: connecting to wifid...
** INFO: dispctl.vala:295: connecting to nm...
** INFO: dispctl.vala:306: connecting to dispd...
** INFO: dispctl.vala:317: fetching from wifid...
** INFO: dispctl.vala:164: found wireless interface: wlan0
** INFO: dispctl.vala:322: fetching from nm...
** INFO: dispctl.vala:327: fetching from wfd...
** INFO: dispctl.vala:355: wifid is acquiring ownership of wlan0...
** INFO: dispctl.vala:374: wait for P2P supporting status...
** INFO: dispctl.vala:379: start P2P scanning...
miracle-dispctl: wait for peer '00:00:00:00:00:00'...
** INFO: dispctl.vala:176: peer added: 00:00:00:00:00:00@3 (Galaxy Grand2)
** INFO: dispctl.vala:188: sink added: 00:00:00:00:00:00@3
** INFO: dispctl.vala:176: peer added: 00:00:00:00:00:00@3 (Galaxy Grand2)
** INFO: dispctl.vala:188: sink added: 00:00:00:00:00:00@3
** INFO: dispctl.vala:422: forming P2P group with ca:a8:23:6b:85:6c (Galaxy Grand2)...
miracle-dispctl: failed to cast to wireless display: timeout to wait for property Connected change
** INFO: dispctl.vala:581: wifid is releasing ownership of wlan0...
** INFO: dispctl.vala:425: failed to form P2P group: lost
miracle-dispctl: Bye
```

**Comment by alexanderadam** [comment]
wow, this looks impressive! @derekdai any chance that the mentioned points are getting fixed? It looks like you did an awesome amount of work!

**Comment by albfan** [comment]
@derekdai I just merge #135 so part of this PR can be rebased on top of that.

I will use your work on systemd services to fix #98, as using `--lazy-managed` allows to run it without any harm.

I decide to merge that PR trying again this one (founding that service running with `--lazy-managed`

I will rebase my branch https://github.com/albfan/miraclecast/tree/derekdai-master-squashed on top of master and try to split it into atomic changes.

Need to look again carefully as I feel lot more treasures are included in these PR

About this PR, My tries with external devices (were I don't control the miracast implementation) do not pass from the handshaking, but using my raspberry pi (now raspbian has systemd updated enough) I think I can get progress and see what is blocking these from being merged

**Comment by sunbearc22** [comment]
@albfan I am branching out from [here](https://github.com/albfan/miraclecast/issues/301#issuecomment-435837335) per your request.

I have tried  `miracle-dispctl -i xxxxx -p 16:bb:6e:xx:xx:xx -w 00000xxxxxxxxxxxxxx`. There is connection between the Samsung Smart TV and my desktop but the connection is lost almost immediately (evident from TV's message).  

**Q1:** How/where can I find the trace log file of miracle-wifid?
**Q2:** What should I do next to fix the connection issue?


**Comments:** 
1. The `-i` (i.e. interface name) value is the name of the desktop wifi card and can be seen from `sudo ifconfig`
2. Discovered that options `-i` and `-p` are essential.  The option `-p` requires the TV wireless MAC address. However, as I had previously describe [here](https://github.com/albfan/miraclecast/issues/301#issuecomment-433084796), I had to use a MAC address where by the first two digits from the left had to be amended as evident by the MAC address provided by @albfan branch `miracle-wifid` trace log.
3. For option `-w`, I had used the `miracle-dispctl` -w default wfd-subelems and also the wfd-subelems of the smart TV obtained from previous `miracle-wifid` trace log.

**Comment by ra100** [comment]
I tried to build these changes and got error while `make`:
```
miraclecast/res/dispctl.vala:807.2-807.18: error: 1 missing arguments for `void GLib.Application.set_default (GLib.Application?)'
	app.set_default();
	^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 2 warning(s)
res/CMakeFiles/miracle-dispctl.dir/build.make:80: recipe for target 'res/dispctl_valac.stamp' failed
make[2]: *** [res/dispctl_valac.stamp] Error 1
CMakeFiles/Makefile2:528: recipe for target 'res/CMakeFiles/miracle-dispctl.dir/all' failed
make[1]: *** [res/CMakeFiles/miracle-dispctl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by rfolland** [comment]
Hi albfan,

What is the status of the WIP on source side Miraclecast? I have tried it and end up with an error when the app does not detect that connection is successful:
```
miracle-dispctl: failed to cast to wireless display: timeout to wait for property Connected change
```
Is there a setup which works, or is this the current status? Then I suppose some work is required to get the Connected status from dbus and move on?

**Comment by albfan** [comment]
It is not working for me too. We could check https://github.com/benzea/gnome-screencast and see what is different (not easy to do)

**Comment by rfolland** [comment]
> It is not working for me too. We could check https://github.com/benzea/gnome-screencast and see what is different (not easy to do)

Thanks! I will try it out.

**Comment by redbrain** [comment]
Is this PR somewhat functional yet? I'd like to use Miraclecast as a source but it seems like progress is stalling.

**Comment by fsevenm** [comment]
2021, and I am still waiting.

**Comment by albfan** [comment]
We love helpful contributions like @piranna one. Per my understanding he has the finish changes and a good reason to not push them.

Deleting ranting as always

**Comment by hypertextPreprocessor** [comment]
sorry, I use this commit complie failed at make process. the error message shows 
image
vala version : Vala 0.56.0
libglib version : libglib2.0-0
systemd version : 249 (249.11-0ubuntu3.12)
and I do checked [valadoc](https://valadoc.org/gio-2.0/GLib.DBus.html) ,it (the BusType) indeed has "get_address_sync" method , it has enum type though, see below:
image
Where was I wrong ? How can I complie this WIP?

**Pull request closed without merging**
