### PR TITLE
[WIP] Streaming to Microsoft Wireless Display dongle

### PR DESCRIPTION
**Pull request by Lqp1**
(as asked in #136 I'm creating a dedicated PR here)

Hello!

First of all, thanks for that great work!

I'm trying to make a Microsoft Wireless Display dongle work with my Linux machine (so, using miracast as a source), and I have some issues. I read most of the past issues and comments regarding MS dongle and source side implementation, and here's what I did in my fork:

* Used still opened PR to make this compile on Gentoo (no systemd)
* Added squashed branch from @derekdai to support source implementation
* Added your work to support windows
* Disabled PIN security on my dongle (I saw that was not supported yet, and indeed, p2p group was not created)
* Started wifid with traces
* Used dispctl to attempt connection

Result: P2P connection is done (I can see the group, the dhcp lease...), but RTSP is not established; I made a Wireshark capture to see what's happening, and looks like the dongle closes the connection when it receives our payload:

```
OPTIONS * RTSP/1.0
Require: org.wfa.wfd1.0
CSeq: 1

RTSP/1.0 200 OK
CSeq: 1
Date: Thu Jan  1 01:31:56 1970
Public: org.wfa.wfd1.0, GET_PARAMETER, SET_PARAMETER

OPTIONS * RTSP/1.0
CSeq: 1
Require: org.wfa.wfd1.0
User-Agent: MSFT-WDD

RTSP/1.0 200 OK
Public: org.wfa.wfd1.0, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER
Date: Wed, 11 Nov 2020 13:38:29 +0000
CSeq: 1

GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Content-Length: 57
Content-Type: text/parameters
CSeq: 2

wfd_video_formats
wfd_audio_codecs
wfd_client_rtp_ports
RTSP/1.0 400 BAD REQUEST
CSeq: 2
```
I don't know if that project is still under active development, but if there is something I can do to help, I would be glad to do so :) Also, if you have any input on how I can try to make this works, it would be nice!

Bw

### CODE REVIEW

**Comment by Lqp1** [comment]
I made a quick test to start validating Microsoft Miracast implementation: using a windows 10 machine as source to this laptop hosting Miraclecast as sink is working fine.

I'll have a look at gnome-network-displays as you suggested to see if I can find something :)

**Comment by albfan** [comment]
I'd check if that allows to source screen to another miraclecast or gnome-network-displays (to remove the microsoft extension part for it)

**Comment by Lqp1** [comment]
Thanks for your input,

I installed miraclecast on a second laptop (let's call it Sink) to use it as a sink, but I don't know if this is a bug or a driver issue on it, but P2P group is very hard to setup; looks like sometimes they both act as GO at same time and start both DHCP server, or the contrary, with 2 DHCP client. This does not happen with Microsoft dongle as sink, or using a samsung tablet as source. Always the two laptops.
 
Anyway, I managed to open a gstreamer link between Sink and Source, but had to make two small changes:
* expose `XAUTHORITY` before starting `gstencoder` in `dispd-encoder`, otherwise I get something like:
```Error spawning command line 'dbus-launch --autolaunch=970be6bbf9ff49009918057c308cf56e --binary-syntax --close-stderr': Child process exited with code 1```
* fix parsing of audio codecs, otherwise LPCM codec that was introduced was leading to bad parsing and it was just failing.

I can reproduce 100% of time the bad request issue with MS dongle; I started to tweak the parameters but not luck for now. I'll try to see if I can make a wireshark capture of RTSP exchange from a Windows machine.

**Comment by linus-ha** [comment]
I've tested your fork / PR and am really happy to see Windows 10 "connect"/screen sharing working! Working flawlessly with:
- Windows 10 (20H2)
- Samsung Galaxy S8 (SM-N950F; Android 9)

**Comment by albfan** [comment]
Still some fixed properties needs to be retrieved from handshake to merge this

**Comment by Lqp1** [comment]
Agreed! I don't have the time for now, I'll try to resume this work when I have some free time

**Comment by albfan** [comment]
with https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#extend-request-protocol

hardcoded parts could be removed from PR.

Still #4 would be the main PR, but I will review this too to see if there's any further improvement

**Comment by albfan** [comment]
Please any work on this should be done on top of #455

**Pull request closed without merging**
