### PR TITLE
WIP: Openrc support

### PR DESCRIPTION
**Pull request by akhuettel**
* Introduce a cmake option -DENABLE_SYSTEMD=OFF (ON is the default)
* Use elogind
* Work around absence of journald

Only build tested so far.

### CODE REVIEW

**Comment by albfan** [comment]
Seems to me a tremendous effort to remove systemd. Remember there is an implementation without systemd in:

https://github.com/albfan/miraclecast/issues/3#issuecomment-228023926

All these commits should be squashed as they are not atomic in any way, all try to remove systemd dependency.

Anyway doesn't seem to be compilable code since you still include sd-bus headers:

https://github.com/akhuettel/miraclecast/blob/openrc/src/ctl/sinkctl.c#L33

As CI demonstrate:

https://semaphoreci.com/albfan/miraclecast-2/branches/pull-request-317/builds/1 

We can setup a CI for this branch and build under a Gentoo Dockerfile, to follow your progress.

I'm gonna flag it as a WIP by now

**Comment by akhuettel** [comment]
Not sure what the CI does (especially since it builds with systemd support); need to check in detail. Later, slighly busy atm...

elogind is a separate package here, and includes the sd-bus headers.

**Comment by albfan** [comment]
It just build using a Dockerfile.

Modify it here (maybe better add a new RUN step)

https://github.com/albfan/miraclecast/blob/master/Dockerfile#L32

so it build with and without systemd

**Comment by joakim-tjernlund** [comment]
Latest elogind has journal support so you should not need to do src mods.

**Comment by albfan** [comment]
Superseed by #441

**Pull request closed without merging**
